Fixed code output error

diff --git a/0x07-networking_basics/5-is_the_host_on_the_network b/0x07-networking_basics/5-is_the_host_on_the_network
--- a/0x07-networking_basics/5-is_the_host_on_the_network
+++ b/0x07-networking_basics/5-is_the_host_on_the_network
@@ -6,4 +6,8 @@ if [ -z "$1" ]; then
 	exit 1
 fi
 
+if ! [[ $1 =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
+    echo "Invalid IP Address format. Please provide a valid IP Address."
+    exit 1
+
 ping -c 5 "$1"
